apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - image: dockersamples/examplevotingapp_worker
          name: worker
          env:
            - name: BACKUP_API_URL
              value: "https://ip5yhhrbvi.execute-api.us-east-1.amazonaws.com/prod/voting_resul"
