name: Build and Push all images to ECR

on:
  push:
    branches: [main, test, developer]

jobs:
  set_namespace:
    runs-on: ubuntu-latest
    outputs:
      namespace: ${{ steps.setenv.outputs.namespace }}
    steps:
      - name: Set environment namespace
        id: setenv
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "namespace=prod" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_name }}" == "test" ]]; then
            echo "namespace=test" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_name }}" == "developer" ]]; then
            echo "namespace=dev" >> $GITHUB_OUTPUT
          fi

  build_and_push:
    runs-on: ubuntu-latest
    needs: set_namespace
    outputs:
      image_tag: ${{ steps.set_tag.outputs.image_tag }}
      ecr_url: ${{ steps.read_url.outputs.ecr_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configurar credenciales temporales de AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name voting-cluster

      - name: Pull url of ecr from kubernet secret
        id: read_url
        run: |
          ECR_URL_ENCODED=$(kubectl get secret ecr-url -n default -o jsonpath="{.data.ECR_REPO_URL}")
          ECR_URL=$(echo "$ECR_URL_ENCODED" | base64 --decode | base64 --decode) 
          echo "ecr_url=$ECR_URL" >> $GITHUB_OUTPUT

      - name: Login to ECR
        run: |
          registry=${{ steps.read_url.outputs.ecr_url }}
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $registry

      - name: Determine image tag
        id: set_tag
        run: |
          ENVIRONMENT=${{ needs.set_namespace.outputs.namespace }}
          BUILD_DATE=$(date +%Y%m%d)
          BUILD_NUMBER=${{ github.run_number }}
          TAG="${ENVIRONMENT}-${BUILD_DATE}-${BUILD_NUMBER}"
          echo "image_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build, tag and push voting-worker image
        run: |
          docker build -t voting-worker ./worker
          docker tag voting-worker:latest ${{ steps.read_url.outputs.ecr_url }}:${{ steps.set_tag.outputs.image_tag }}
          docker push ${{ steps.read_url.outputs.ecr_url }}:${{ steps.set_tag.outputs.image_tag }}

      - name: Build, tag and push voting-result image
        run: |
          docker build -t voting-result ./result
          docker tag voting-result:latest ${{ steps.read_url.outputs.ecr_url }}:${{ steps.set_tag.outputs.image_tag }}
          docker push ${{ steps.read_url.outputs.ecr_url }}:${{ steps.set_tag.outputs.image_tag }}

      - name: Build, tag and push voting-vote image
        run: |
          docker build -t voting-vote ./vote
          docker tag voting-vote:latest ${{ steps.read_url.outputs.ecr_url }}:${{ steps.set_tag.outputs.image_tag }}
          docker push  ${{ steps.read_url.outputs.ecr_url }}:${{ steps.set_tag.outputs.image_tag }}

  deploy:
    needs: [build_and_push, set_namespace]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name voting-cluster

      - name: Update images with new tag
        run: |
          sed -i -E "s|image:.*|image: ${{ needs.build_and_push.outputs.ecr_url }}:${{ needs.build_and_push.outputs.image_tag }}|" k8s-specifications/worker-deployment.yaml
          sed -i -E "s|image:.*|image: ${{ needs.build_and_push.outputs.ecr_url }}:${{ needs.build_and_push.outputs.image_tag }}|" k8s-specifications/vote-deployment.yaml
          sed -i -E "s|image:.*|image: ${{ needs.build_and_push.outputs.ecr_url }}:${{ needs.build_and_push.outputs.image_tag }}|" k8s-specifications/result-deployment.yaml

      - name: Deploy to namespace
        run: |
          kubectl apply -f k8s-specifications/ --namespace=${{ needs.set_namespace.outputs.namespace }}
