name: CI with SonarCloud and Docker Build

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  sonarcloud:
    name: Analyze All Services
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Java (requerido por SonarScanner)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Setup Python para vote/
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Setup Node.js para result/
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Setup .NET para worker/
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      # Install SonarScanner
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: sonarcloud

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build vote service (Python)
        run: docker build -t vote-service ./vote

      - name: Build result service (Node.js)
        run: docker build -t result-service ./result

      - name: Set up .NET for worker
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Build worker service (C#)
        run: docker build -t worker-service ./worker
