name: Run K6 Load Tests

on:
  push:
    branches: [test]

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build K6 Docker image
        run: |
          docker build -t k6-test-image ./testk6

      - name: Run K6 tests in container
        run: |
          docker run --rm k6-test-image
